// npm run i18n — extracts every translatable string into static/i18n/odoo_debug.pot and merges it into each
// static/i18n/<lang>.po.
//   TS:   _t('literal', …) and N_('literal') (template literals / variables are not extracted: always pass a literal)
//   HTML: elements with data-i18n="text,title,…" (the English text / attribute values are the msgids)
// Existing translations are kept, new strings get an empty msgstr (en.po: msgstr = msgid).
// The .po files keep only the strings a source uses. (While the tabs were being ported from the JavaScript extension they
// also kept the unused ones, waiting for their tab: KEEP_UNUSED, off since the last one, Code, was ported.)
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { LANGS, parsePo } from '../src/i18n/i18n.ts';

const KEEP_UNUSED = false;

const ROOT = join(import.meta.dirname, '..');
const SRC = join(ROOT, 'src');
const DIR = join(ROOT, 'static', 'i18n');
const POT = join(DIR, 'odoo_debug.pot');

const files = (dir: string): string[] => readdirSync(dir, { withFileTypes: true }).flatMap((d) =>
  d.isDirectory() ? files(join(dir, d.name)) : /\.(ts|html)$/.test(d.name) && !d.name.endsWith('.d.ts') ? [join(dir, d.name)] : []).sort();
// Literals are decoded with Function (our own source only): exact JS escape semantics for free.
const decode = (lit: string) => new Function(`return ${lit}`)() as string;
const lineOf = (text: string, i: number) => text.slice(0, i).split('\n').length;
// HTML text and attribute values as the browser reads them (what translateDom looks up): entities decoded.
const ENTITIES: Record<string, string> = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: '\u00a0' };
const unescapeHtml = (s: string) => s.replace(/&(#\d+|#x[\da-f]+|\w+);/gi, (m, e: string) =>
  e[0] === '#' ? String.fromCodePoint(e[1]?.toLowerCase() === 'x' ? parseInt(e.slice(2), 16) : Number(e.slice(1))) : ENTITIES[e] ?? m);

const found = new Map<string, string[]>(); // msgid → ["file:line", …] in source order
const add = (msgid: string, ref: string) => { if (!found.has(msgid)) found.set(msgid, []); found.get(msgid)!.push(ref); };

for (const f of files(SRC)) {
  const text = readFileSync(f, 'utf8');
  const rel = relative(ROOT, f);
  if (f.endsWith('.ts')) {
    for (const m of text.matchAll(/(?<![\w.$])(?:_t|N_)\(\s*('(?:[^'\\\n]|\\.)*'|"(?:[^"\\\n]|\\.)*")/g)) add(decode(m[1]!), `${rel}:${lineOf(text, m.index)}`);
  } else {
    for (const m of text.matchAll(/<\w+\b([^>]*)\bdata-i18n="([^"]+)"([^>]*)>([^<]*)/g)) {
      const attrs = m[1]! + m[3]!;
      for (const what of m[2]!.split(',')) {
        const v = what === 'text' ? m[4]!.trim() : attrs.match(new RegExp(`\\b${what}="([^"]*)"`))?.[1];
        if (v) add(unescapeHtml(v), `${rel}:${lineOf(text, m.index)}`);
      }
    }
  }
}

const q = (s: string) => JSON.stringify(s); // PO and JSON share the escapes we need (\" \\ \n \t)
const header = (lang: string) => [
  'msgid ""', 'msgstr ""',
  q('Project-Id-Version: Odoo Debug\n'), q('PO-Revision-Date: \n'), q('Last-Translator: \n'), q('Language-Team: \n'),
  q(`Language: ${lang}\n`), q('MIME-Version: 1.0\n'), q('Content-Type: text/plain; charset=UTF-8\n'), q('Content-Transfer-Encoding: 8bit\n'), '',
].join('\n');
const entry = (id: string, str: string, refs: string[] = []) => `${refs.map((r) => `#: ${r}\n`).join('')}msgid ${q(id)}\nmsgstr ${q(str)}\n`;

writeFileSync(POT, `# Odoo Debug — translation template, generated by \`npm run i18n\`: do not edit by hand.\n${header('')}\n${
  [...found].map(([id, refs]) => entry(id, '', refs)).join('\n')}`);
console.log(`${relative(ROOT, POT)}: ${found.size} strings`);

const holes = (s: string) => (s.match(/%s/g) || []).length;
for (const lang of Object.keys(LANGS)) {
  const file = join(DIR, `${lang}.po`);
  const old = existsSync(file) ? parsePo(readFileSync(file, 'utf8')) : new Map<string, string>();
  const tr = (id: string) => old.get(id) || (lang === 'en' ? id : '');
  const unused = [...old.keys()].filter((id) => !found.has(id));
  const kept = KEEP_UNUSED ? unused : [];
  writeFileSync(file, `# Odoo Debug — ${LANGS[lang as keyof typeof LANGS]}\n${header(lang)}\n${[
    ...[...found].map(([id, refs]) => entry(id, tr(id), refs)),
    ...kept.map((id) => entry(id, old.get(id)!)),
  ].join('\n')}`);
  const missing = [...found.keys()].filter((id) => !tr(id));
  const bad = [...found.keys()].filter((id) => tr(id) && holes(tr(id)) !== holes(id));
  console.log(`${relative(ROOT, file)}: ${found.size - missing.length}/${found.size} translated`
    + (kept.length ? `, ${kept.length} kept for the tabs not ported yet` : unused.length ? `, ${unused.length} unused dropped` : '')
    + (bad.length ? `\n  %s count mismatch: ${bad.map(q).join(', ')}` : '')
    + (missing.length ? `\n  untranslated: ${missing.map(q).join(', ')}` : ''));
}
